# Generated by Django 6.0.1 on 2026-01-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_father_name_employee_mother_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
