# Generated by Django 6.0.1 on 2026-01-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
    ]
