# Generated by Django 6.0.1 on 2026-01-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_employee_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Aadhar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='acc_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='temp0001', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.CharField(default='temp001', max_length=20),
            preserve_default=False,
        ),
    ]
