# Generated by Django 6.0.1 on 2026-01-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_employee_date_of_birth_employee_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, choices=[('BCom', 'B.Com'), ('BSc', 'B.Sc'), ('BA', 'B.A'), ('BTech', 'B.Tech'), ('MCom', 'M.Com'), ('MSc', 'M.Sc'), ('MA', 'M.A'), ('MTech', 'M.Tech')], max_length=10, null=True),
        ),
    ]
