# Generated by Django 6.0.1 on 2026-01-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_employee_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='education',
        ),
        migrations.AddField(
            model_name='employee',
            name='bachelor_degree',
            field=models.CharField(blank=True, choices=[('BCom', 'B.Com'), ('BSc', 'B.Sc'), ('BA', 'B.A'), ('BTech', 'B.Tech')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='master_degree',
            field=models.CharField(blank=True, choices=[('MCom', 'M.Com'), ('MSc', 'M.Sc'), ('MA', 'M.A'), ('MTech', 'M.Tech')], max_length=10, null=True),
        ),
    ]
