# Generated by Django 6.0.1 on 2026-01-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_employee_education_employee_bachelor_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='generated_at',
            field=models.DateField(blank=True,null=True),
            preserve_default=False,
        ),
    ]
