# Generated by Django 6.0.1 on 2026-01-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_employee_generated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='generated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
