# Generated by Django 6.0.1 on 2026-01-30 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_employee_generated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shift')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
