# Generated by Django 6.0.1 on 2026-02-06 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('LWP', 'Leave With Pay'), ('Leave', 'Leave'), ('Holiday', 'Holiday'), ('Absent', 'Absent')], default='Absent', max_length=20),
        ),
    ]
