# Generated by Django 6.0.1 on 2026-02-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_attendance_is_processed_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
