# Generated by Django 6.0.1 on 2026-02-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_attendance_punch_in_alter_attendance_punch_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='weekly_off',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Sunday', max_length=10),
        ),
    ]
