# Generated by Django 6.0.1 on 2026-02-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_shift_weekly_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lwp_balance',
            field=models.IntegerField(default=0),
        ),
    ]
