# Generated by Django 6.0.1 on 2026-03-05 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_attendanceregularization'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='emp_esic_percent',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=5),
        ),
        migrations.AddField(
            model_name='salary',
            name='emp_pf_percent',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
        migrations.AddField(
            model_name='salary',
            name='employer_esic_percent',
            field=models.DecimalField(decimal_places=2, default=3.25, max_digits=5),
        ),
        migrations.AddField(
            model_name='salary',
            name='employer_pf_percent',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
        migrations.AddField(
            model_name='salary',
            name='esic_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salary',
            name='pf_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lwp_days', models.IntegerField(default=0)),
                ('lwp_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emp_pf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employer_pf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emp_esic', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employer_esic', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
