# Generated by Django 6.0.1 on 2026-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_salary_emp_esic_percent_salary_emp_pf_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='emp_esic_percent',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='emp_pf_percent',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='employer_esic_percent',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='employer_pf_percent',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='esic_applicable',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='pf_applicable',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='salary',
            name='emp_esic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='emp_pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='employer_esic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='employer_pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
