# Generated by Django 6.0.1 on 2026-03-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_salary_emp_esic_percent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='lwp_days',
            new_name='absent_days',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='lwp_deduction',
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='extra_leave_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='present_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='working_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='emp_esic',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='emp_pf',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='employer_esic',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='employer_pf',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='app.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
