# Generated by Django 6.0.1 on 2026-03-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_lwp_days_monthlysalary_absent_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='extra_leave_days',
            field=models.IntegerField(default=0),
        ),
    ]
