# Generated by Django 6.0.1 on 2026-03-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_monthlysalary_extra_leave_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='working_days',
            field=models.IntegerField(default=0),
        ),
    ]
