# Generated by Django 6.0.1 on 2026-03-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_monthlysalary_leave_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='half_days',
            field=models.IntegerField(default=0),
        ),
    ]
