# Generated by Django 6.0.1 on 2026-03-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
