# Generated by Django 6.0.1 on 2026-03-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_monthlysalary_allowance_monthlysalary_basic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('ACCOUNTS', 'Accounts'), ('EMPLOYEE', 'Employee'), ('STORE_MANAGER', 'Store Manager')], default='EMPLOYEE', max_length=20),
        ),
    ]
