# Generated by Django 6.0.1 on 2026-03-20 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_monthlysalary_allowance_monthlysalary_basic_and_more'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, 'Outstanding'), (4, 'Exceeds Expectations'), (3, 'Meets Expectations'), (2, 'Needs Improvement'), (1, 'Poor')])),
                ('comments', models.TextField()),
                ('review_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to='app.employee')),
            ],
        ),
    ]
