# Generated by Django 6.0.1 on 2026-03-20 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_monthlysalary_allowance_monthlysalary_basic_and_more'),
        ('performance', '0002_performancereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_created', to='app.employee'),
        ),
    ]
