# Generated by Django 6.0.1 on 2026-03-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_goal_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='achieved_value',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
