# Generated by Django 6.0.1 on 2026-03-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_alter_goal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='target_value',
        ),
    ]
