# Generated by Django 6.0.1 on 2026-03-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_remove_goal_target_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
