# Generated by Django 6.0.1 on 2026-03-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_goal_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='submitted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
